name: Novu Benchmark
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    name: Build with Docker
    strategy:
      matrix:
        os: [ubuntu-20.04, nscloud]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init novu

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          context: ./novu
          file: ./novu/apps/web/Dockerfile

  nsc-build:
    name: Build with Namespace
    strategy:
      matrix:
        os: [ubuntu-20.04, nscloud]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init novu

      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0

      - uses: docker/build-push-action@v4
        with:
          context: ./novu
          file: ./novu/apps/web/Dockerfile
