name: Novu Benchmark
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "45 * * * *"

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init novu

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          context: ./novu
          file: ./novu/apps/web/Dockerfile

  nsc-build:
    name: Build with Namespace
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init novu

      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0

      - uses: docker/build-push-action@v4
        with:
          context: ./novu
          file: ./novu/apps/web/Dockerfile

  notify-failures:
    name: Notify on build failures
    needs:
      - docker-build
      - nsc-build
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    if: failure() && needs.docker-build.result == 'success' && needs.nsc-build.result == 'failure'
    steps:
      - uses: ruby/action-slack@v3.2.1
        with:
          payload: |
            {
              "attachments": [{
                "title": "Namespace build failed while Docker build passed! Check now: ${{ job.status }}: ${{ github.workflow }}",
                "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "text": "See the link",
                "fields": [],
                "footer": "",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
