name: Upstream Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "35 * * * *" # hourly sync, triggers a benchmark only if upstream was changed.

jobs:
  sync:
    name: Upstream Sync
    runs-on: nscloud
    concurrency: 
      group: sync_upstream
      cancel-in-progress: true
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use a custom PAT to push to enable triggering on_push workflows:
          # https://github.com/orgs/community/discussions/25702
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Git Config
        run: |
          git config --global user.name github-actions
          git config --global user.email noreply+github-actions@namespacelabs.com

      - name: Sync Git Submodules
        run: |
          git submodule init
          git submodule update --remote --merge

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Sync target upstreams" || echo "Nothing to commit"
          git push origin main
